### ISSUE TITLE
validation generator size assert

### ISSUE THREAD

**Issue by DrAnaximandre** [tboquet/python-alp#40]
- [x] check if the size of gen and gen_val are the same for the keras backend
- [x] modify the function in utils that handles the pickling of the generators
- case 1: size gen and size gen val are equal
- case 2 :  size gen and size gen val are different and size gen val is 1 (many to one)
- case 3 :  size gen and size gen val are different and size gen is 1 (one to many)

else error

**Comment by tboquet** [comment]
Closing, done in #42 .
